# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: change_det.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63hange_det.proto\x12\x03\x64\x65t\"(\n\x08\x44\x65tInput\x12\x0e\n\x06target\x18\x01 \x01(\x0c\x12\x0c\n\x04\x62\x61se\x18\x02 \x01(\x0c\"^\n\x04Rect\x12\x0c\n\x04left\x18\x01 \x01(\x02\x12\x0b\n\x03top\x18\x02 \x01(\x02\x12\r\n\x05right\x18\x03 \x01(\x02\x12\x0e\n\x06\x62ottom\x18\x04 \x01(\x02\x12\r\n\x05label\x18\x05 \x01(\x05\x12\r\n\x05logit\x18\x06 \x01(\x02\"%\n\tDetResult\x12\x18\n\x05\x62oxes\x18\x01 \x03(\x0b\x32\t.det.Rect20\n\x03\x44\x65t\x12)\n\x06\x44\x65tect\x12\r.det.DetInput\x1a\x0e.det.DetResult\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'change_det_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DETINPUT._serialized_start=25
  _DETINPUT._serialized_end=65
  _RECT._serialized_start=67
  _RECT._serialized_end=161
  _DETRESULT._serialized_start=163
  _DETRESULT._serialized_end=200
  _DET._serialized_start=202
  _DET._serialized_end=250
# @@protoc_insertion_point(module_scope)
